# Generated by Django 4.1 on 2022-08-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='', max_length=70)),
                ('Board_type', models.CharField(default='', max_length=70)),
                ('STM32Family', models.CharField(default='', max_length=70)),
                ('reference', models.CharField(default='', max_length=70)),
                ('Status', models.CharField(default='', max_length=70)),
                ('Owner', models.CharField(default='', max_length=70)),
                ('Needed', models.CharField(default='', max_length=70)),
                ('Quantity', models.CharField(default='', max_length=70)),
                ('DHL_tracking', models.CharField(default='', max_length=70)),
                ('name_Reception', models.CharField(default='', max_length=70)),
                ('Date_reception', models.CharField(default='', max_length=70)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
    ]
