# Generated by Django 4.1.1 on 2022-10-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_management', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_management.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_management.user')),
            ],
        ),
    ]
